AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API Infrastructure for ERP Serverless

Parameters:
  Environment:
    Type: String
    Default: cert
  CreateSaleFunctionArn:
    Type: String
  LogRetentionDays:
    Type: Number
    Default: 7

Resources:
  # --- INFRASTRUCTURE: API ---
  SalesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.integration.status $context.integration.latency'
      # REFERENCIAMOS EL ARCHIVO EXTERNO:
      DefinitionUri: ./api/sales-api.yaml

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/SalesApi-${Environment}"
      RetentionInDays: !Ref LogRetentionDays

  # --- PERMISSIONS ---
  CreateSalePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateSaleFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SalesApi}/*"

Outputs:
  SalesApiUrl:
    Description: "API Gateway endpoint URL for Sales module"
    Value: !Sub "https://${SalesApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/sales/"
  SalesApiId:
    Description: "The ID of the Sales API"
    Value: !Ref SalesApi
