AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Events Infrastructure for ERP Serverless

Parameters:
  Environment:
    Type: String
    Default: cert

Resources:
  # --- INFRASTRUCTURE: EVENTS ---
  ErpEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "ErpEventBus-${Environment}"

Outputs:
  EventBusName:
    Description: "The name of the ERP Event Bus"
    Value: !Ref ErpEventBus
  EventBusArn:
    Description: "The ARN of the ERP Event Bus"
    Value: !GetAtt ErpEventBus.Arn
